### PR TITLE
Fix: fixed a potential vulnerability in `/api/chat/get_file` endpoint.

### LINKED ISSUE #1675: [Security] Unauthorized Path Traversal Vulnerability in /api/chat/get_file of AstrBotDevs/AstrBot
### 发生了什么

# Unauthorized Path Traversal Vulnerability in /api/chat/get_file of AstrBotDevs/AstrBot

# Summary

Attackers can exploit a Path traversal vulnerability by manipulating the filename parameter in the /api/chat/get_file function to read files on the target host. The vulnerability originates from line 58 in `AstrBot/astrbot/dashboard/routes
/chat.py`, where the code `filename = request.args.get("filename")` does not sanitize the filename.

# POC

## Build

Follow these steps to set up the test environment:

```shell
pip install uv
git clone https://github.com/AstrBotDevs/AstrBot && cd AstrBot
uv run main.py
```

## Reproduce

- run：`curl -L http://0.0.0.0:6185/api/chat/get_file?filename=../../../data/cmd_config.json`

This will read cmd_config.json to leak **llm key**、**username** and **password**(md5)!!!

# Discussion

```python
    async def get_file(self):
        filename = request.args.get("filename")
        if not filename:
            return Response().error("Missing key: filename").__dict__

        try:
            with open(os.path.join(self.imgs_dir, filename), "rb") as f:
                if filename.endswith(".wav"):
                    return QuartResponse(f.read(), mimetype="audio/wav")
                elif filename.split(".")[-1] in self.supported_imgs:
                    return QuartResponse(f.read(), mimetype="image/jpeg")
                else:
                    return QuartResponse(f.read())  # <------------- Here

        except FileNotFoundError:
            return Response().error("File not found").__dict__
```

Obviously, this route directly uses the passed file name as the target path to read the file. One of my suggestions for fixing this is to only access this route after the user is authenticated.

# Impact

The potential harms of this vulnerability include:

- Information leak.

# Credit

The vulnerability was discovered by 360 VRI.

## Build

Follow these steps to set up the test environment:

```shell
pip install uv
git clone https://github.com/AstrBotDevs/AstrBot && cd AstrBot
uv run main.py
```

## Reproduce

- run：`curl -L http://0.0.0.0:6185/api/chat/get_file?filename=../../../data/cmd_config.json`

This will read cmd_config.json to leak **llm key**、**username** and **password**(md5)!!!

### AstrBot 版本、部署方式（如 Windows Docker Desktop 部署）、使用的提供商、使用的消息平台适配器

v3.5.12

### 操作系统

Linux

### 报错日志

[2025-05-29 17:40:03 +0800] [22412] [INFO] Running on http://0.0.0.0:6185 (CTRL + C to quit)
[2025-05-29 17:40:05 +0800] [22412] [INFO] 127.0.0.1:49500 GET /api/chat/get_file 1.1 200 2775 2270

### 你愿意提交 PR 吗？

- [ ] 是的，我愿意提交 PR!

### Code of Conduct

- [x] 我已阅读并同意遵守该项目的 [行为准则](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。

### PR DESCRIPTION
**Pull request by Soulter**
I have fixed a potential vulnerability in the `/api/chat/get_file` endpoint that could allow unauthorized access to files by ensuring the request has a jwt token.

Fixes #1675 

### Motivation

The previous implementation did not enforce proper authentication for the /api/chat/get_file endpoint, which could allow unauthorized users to access sensitive files. This posed a security risk and needed to be addressed.

### Modifications

1. All requests to the /api/chat/get_file endpoint must now include a valid JWT token.
2. Added validation logic to verify the filename parameter in the route, preventing potential misuse or path traversal.

### Check

- [x] 😊 我的 Commit Message 符合良好的[规范](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x] 👀 我的更改经过良好的测试
- [x] 🤓 我确保没有引入新依赖库，或者引入了新依赖库的同时将其添加到了 `requirements.txt` 和 `pyproject.toml` 文件相应位置。
- [x] 😮 我的更改没有引入恶意代码

好的，这是将 pull request 总结翻译成中文的结果：

## Sourcery 总结

使用 JWT 认证和路径遍历检查来保护 `/api/chat/get_file` 端点，并改进前端媒体处理，以使用具有适当生命周期管理的缓存 blob URL。

新特性：
- 在 ChatPage.vue 中通过新的 getMediaFile 方法缓存并提供媒体文件作为 blob URL

Bug 修复：
- `/api/chat/get_file` 需要有效的 JWT，并将其从未经身份验证的端点列表中删除
- 通过验证 `/api/chat/get_file` 端点中的 filename 参数来防止路径遍历

增强功能：
- 重构媒体暂存以单独存储文件名并按需生成 blob URL
- 引入 mediaCache 和 cleanupMediaCache 来管理 blob URL 缓存和撤销

<details>
<summary>Original summary in English</summary>

## Summary by Sourcery

Secure the `/api/chat/get_file` endpoint with JWT authentication and path traversal checks, and revamp the frontend media handling to use cached blob URLs with proper lifecycle management.

New Features:
- Cache and serve media files as blob URLs in ChatPage.vue via a new getMediaFile method

Bug Fixes:
- Require a valid JWT for `/api/chat/get_file` and remove it from the unauthenticated endpoints list
- Prevent path traversal by validating the filename parameter in the `/api/chat/get_file` endpoint

Enhancements:
- Refactor media staging to store filenames separately and generate blob URLs on-demand
- Introduce mediaCache and cleanupMediaCache to manage blob URL caching and revocation

</details>

### CODE REVIEW

File: dashboard/src/views/ChatPage.vue [hunk 1]
```diff
@@ -282,7 +282,10 @@ export default {
             try {
                 const response = await axios.get('/api/chat/get_file', {
                     params: { filename },
-                    responseType: 'blob'
+                    responseType: 'blob',
+                    headers: {
+                        'Authorization': 'Bearer ' + localStorage.getItem('token')
+                    }
```
Comment (Soulter) [inline dashboard/src/views/ChatPage.vue]: 这个似乎是没必要的，已经在 https://vscode.dev/github/Soulter/AstrBot/blob/feat/alkaid/dashboard/src/main.ts#L24-L30 实现
